# Generated by Django 3.0.5 on 2021-02-13 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=35, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=35, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('about_text', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('about_html', models.TextField(blank=True, default=None, null=True)),
                ('avatar_hash', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('display_picture', models.NullBooleanField(default=False)),
                ('homepage', models.URLField(blank=True, default=None, null=True)),
                ('twitter', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('github', models.CharField(blank=True, default=None, max_length=39, null=True)),
                ('comments', models.IntegerField(default=0)),
                ('links', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
