# Generated by Django 3.0.5 on 2021-02-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qauser',
            old_name='homepage',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='qauser',
            name='avatar_hash',
        ),
        migrations.RemoveField(
            model_name='qauser',
            name='display_picture',
        ),
        migrations.AddField(
            model_name='qauser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='profile_pic',
            field=models.ImageField(default='profile.png', null=True, upload_to=''),
        ),
    ]
