# Generated by Django 3.0.5 on 2021-02-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210218_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qauser',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
