# Generated by Django 3.0.5 on 2021-02-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210218_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qauser',
            name='about_html',
        ),
        migrations.AddField(
            model_name='qauser',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qauser',
            name='profile_pic',
            field=models.ImageField(default='logo.png', null=True, upload_to=''),
        ),
    ]
