# Generated by Django 3.0.5 on 2021-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210219_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qauser',
            name='facebook',
            field=models.URLField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qauser',
            name='github',
            field=models.URLField(blank=True, default=None, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='qauser',
            name='twitter',
            field=models.URLField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
